# Generated by Django 5.0.4 on 2024-05-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livre',
            new_name='Anime',
        ),
    ]
