# Generated by Django 5.0.4 on 2024-05-02 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0002_rename_livre_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='genre',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='titre',
        ),
        migrations.AddField(
            model_name='anime',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='animeapp.studio'),
        ),
    ]
