# Generated by Django 5.0.4 on 2024-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeapp', '0003_studio_rename_genre_anime_title_remove_anime_titre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='duration',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
